version: '3'
services:
    db:
        image: postgres:10
        restart: always
        command: CREATE DATABASE campagWEB;
        environment:
          POSTGRES_DB: campagWEB
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    
    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080
    backend: 
        image: node:8.1
        volumes: 
            - ./backend:/backend
        ports: 
            - 3000:3000
        command: cd /backend && npm install && node index.js
    frontend:
        image: nginx:1.13
        volumes:
            - ./frontend:/usr/share/nginx/html/
        ports: 
            - 80:80
