version: '3'
services:
    db: 
        image: postgres:10
    backend: 
        image: node:10
        volumes: 
            - ./backend:/backend
        ports: 
            - 3000:3000
        command: bash -c "cd /backend && npm i && node index.js"
    frontend:
        image: nginx:1.13
        volumes:
            - ./frontend/dist:/usr/share/nginx/html/
        ports: 
            - 80:80
